[package]
name = "yimu"
version = "0.1.0"
authors = ["yfaming <yfaming@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.17"
bytes = "0.4.12"
env_logger = "0.7.1"
failure = "0.1.6"
futures = "0.3.1"
futures-util-preview = "0.3.0-alpha.19"
log = "0.4.8"
tokio = "0.2.0-alpha.6"
trust-dns-resolver = "0.18.0-alpha.1"

[profile.release]
lto = true
